CREATE SEQUENCE  IF NOT EXISTS order_item_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS order_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS payment_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS product_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS role_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS shipment_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS storage_item_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS storage_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS user_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE order_ (
  id BIGINT NOT NULL,
   customer_id BIGINT NOT NULL,
   order_status VARCHAR(255) NOT NULL,
   order_number VARCHAR(255),
   CONSTRAINT pk_order_ PRIMARY KEY (id)
);

CREATE TABLE order_item (
  id BIGINT NOT NULL,
   product_id BIGINT NOT NULL,
   count BIGINT NOT NULL,
   order_id BIGINT NOT NULL,
   CONSTRAINT pk_order_item PRIMARY KEY (id)
);

CREATE TABLE payment (
  id BIGINT NOT NULL,
   order_id BIGINT,
   cost DECIMAL(19, 2) NOT NULL,
   payment_status VARCHAR(255) NOT NULL,
   CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE product (
  id BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   price DECIMAL(19, 2),
   description VARCHAR(4000),
   product_discount VARCHAR(255),
   CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE role (
  id BIGINT NOT NULL,
   role_type VARCHAR(255) NOT NULL,
   CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE shipment (
  id BIGINT NOT NULL,
   order_id BIGINT NOT NULL,
   delivery_address VARCHAR(255) NOT NULL,
   shipment_status VARCHAR(255) NOT NULL,
   CONSTRAINT pk_shipment PRIMARY KEY (id)
);

CREATE TABLE storage (
  id BIGINT NOT NULL,
   storage_number VARCHAR(255) NOT NULL,
   CONSTRAINT pk_storage PRIMARY KEY (id)
);

CREATE TABLE storage_item (
  id BIGINT NOT NULL,
   product_id BIGINT NOT NULL,
   count BIGINT NOT NULL,
   storage_id BIGINT NOT NULL,
   storage_item_discount VARCHAR(255),
   CONSTRAINT pk_storage_item PRIMARY KEY (id)
);

CREATE TABLE user_ (
  id BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   login VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   CONSTRAINT pk_user_ PRIMARY KEY (id)
);

CREATE TABLE user__roles (
  roles_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL,
   CONSTRAINT pk_user__roles PRIMARY KEY (roles_id, user_id)
);

ALTER TABLE order_item ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES order_ (id);

ALTER TABLE order_item ADD CONSTRAINT FK_ORDER_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE order_ ADD CONSTRAINT FK_ORDER__ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES user_ (id);

ALTER TABLE payment ADD CONSTRAINT FK_PAYMENT_ON_ORDER FOREIGN KEY (order_id) REFERENCES order_ (id);

ALTER TABLE shipment ADD CONSTRAINT FK_SHIPMENT_ON_ORDER FOREIGN KEY (order_id) REFERENCES order_ (id);

ALTER TABLE storage_item ADD CONSTRAINT FK_STORAGE_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE storage_item ADD CONSTRAINT FK_STORAGE_ITEM_ON_STORAGE FOREIGN KEY (storage_id) REFERENCES storage (id);

ALTER TABLE user__roles ADD CONSTRAINT FK_USEROL_ON_ROLE FOREIGN KEY (roles_id) REFERENCES role (id);

ALTER TABLE user__roles ADD CONSTRAINT FK_USEROL_ON_USER FOREIGN KEY (user_id) REFERENCES user_ (id);